# Generated by Django 3.2 on 2021-05-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='full_name',
            field=models.CharField(default='salaheddine el azzaouy', max_length=50),
            preserve_default=False,
        ),
    ]
