# Generated by Django 3.2 on 2021-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about_intor'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default='dad', upload_to='profile'),
            preserve_default=False,
        ),
    ]
