# Generated by Django 3.2 on 2021-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_itemes',
            name='image',
            field=models.ImageField(default='sfsafsafas', upload_to='porfolio'),
            preserve_default=False,
        ),
    ]
